name: Deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: web-site
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: ./.github/actions/setup-mise
      - uses: ./.github/actions/setup-js

      - name: Build
        run: nr build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          packageManager: npm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=lapriere-website

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ steps.deploy.outputs.deployment-url }}
          ref: ${{ github.head_ref || github.ref_name }}

    outputs:
      deploy_url: ${{ steps.deploy.outputs.deployment-url }}

  e2e-test:
    needs: deploy
    uses: ./.github/workflows/e2e.yaml
    permissions:
      deployments: write
      actions: write
      pull-requests: write
      contents: write
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    with:
      url: ${{ needs.deploy.outputs.deploy_url }}
