name: Deploy

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-js

      - name: Build
        run: nr build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=lapriere-website
    outputs:
      deploy_url: ${{ steps.deploy.outputs.deployment-url }}

  E2E:
    needs: deploy
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged != true
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
    steps:
      - uses: actions/checkout@v4

      - run: |
          apt update && apt install fonts-noto

      - uses: ./.github/actions/setup-js

      - name: Run Playwright tests
        continue-on-error: true
        run: na playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ needs.deploy.outputs.deploy_url }}

      - name: Remove download attribute
        run: |
          sed -i 's|,download:Kv(e)||g' playwright-report/index.html

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy playwright-report --project-name=lapriere-website-playwright
