name: Playwright Tests

on:
  push:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-js

      - name: Build
        run: nr build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy playwright-report --project-name=lapriere-website
