name: Playwright Updates

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - run: |
          apt-get update && apt-get install -y fonts-noto unzip

      - uses: ./.github/actions/setup-js

      - name: Run Playwright tests
        run: na playwright test -u
        env:
          PLAYWRIGHT_TEST_BASE_URL: https://lapriere.totto2727.dev

      - name: Commit ScreenShot
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git branch -f update-screenshots/${G_HEAD_REF} ${G_HEAD_REF}
          git switch update-screenshots/${G_HEAD_REF}
          git add ./src/playwright
          git commit -m "test: update screenshots. ${G_HEAD_REF}"
          git push --force origin update-screenshots/${G_HEAD_REF}
        env:
          G_HEAD_REF: ${{ github.head_ref }}

      - name: Create PR
        continue-on-error: true
        run: gh pr create --base ${G_HEAD_REF} --head update-screenshots/${G_HEAD_REF} --title "update-screenshots ${G_HEAD_REF}" --body ""
