name: Deploy

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true

permissions:
  deployments: write

jobs:
  E2E:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
    steps:
      - uses: actions/checkout@v4

      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: playwright
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: ./.github/actions/setup-playwright

      - name: Run Playwright tests
        continue-on-error: true
        run: na playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ inputs.url }}
          HOME: /root

      - name: Remove download attribute
        run: |
          sed -i 's|,download:Kv(e)||g' playwright-report/index.html

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy playwright-report --project-name=lapriere-website-playwright

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ steps.deploy.outputs.deployment-url }}
          ref: ${{ github.head_ref || github.ref_name }}
