name: Playwright Tests

on:
  deployment_status:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    permissions:
      contents: read
      deployments: write
      statuses: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-js

      - name: Install Playwright
        run: na playwright install --with-deps

      - name: Run Playwright tests
        run: na playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy playwright-report --project-name=lapriere-website-playwright
