name: VRT Update

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write

jobs:
  vrt-update:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install packages
        run: apt-get update & apt-get install -y git wget

      - name: Install Github CLI
        run: |
          mkdir -p -m 755 /etc/apt/keyrings \
          && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \ && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt-get update \
          && apt-get -y install gh

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: ./.github/actions/setup-playwright

      - name: Run Playwright tests
        run: na playwright test -u --grep @vrt
        env:
          PLAYWRIGHT_TEST_BASE_URL: https://lapriere.totto2727.dev
          HOME: /root

      - name: Commit ScreenShot
        run: |
          set -x
          git config --global --add safe.directory $PWD
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git branch -f update-screenshots/${GITHUB_REF_NAME} ${GITHUB_REF_NAME}
          git switch update-screenshots/${GITHUB_REF_NAME}
          git add ./src/playwright
          git commit -m "test: update screenshots. ${GITHUB_REF_NAME}"
          git push --force origin update-screenshots/${GITHUB_REF_NAME}

      - name: Create PR
        continue-on-error: true
        run: gh pr create --base ${GITHUB_REF_NAME} --head update-screenshots/${GITHUB_REF_NAME} --title "update-screenshots ${GITHUB_REF_NAME}" --body ""
